
IF OBJECT_ID('tempDB..#MASCARA','U') IS NOT NULL DROP TABLE #MASCARA
SELECT 
		CPF 
		,replicate('0',(11 - len(cast(ROW_NUMBER() OVER(ORDER BY CPF) as varchar)))) + cast(ROW_NUMBER() OVER(ORDER BY CPF) as Varchar) AS MASCARA_CPF INTO #MASCARA
	FROM (
		SELECT DISTINCT 
				V.CPF_CNPJ AS CPF
			FROM CRM_DATALAKE.CRM.TRANSACIONAL_VENDA AS V
) AS T

SELECT DISTINCT
		V.CPF_CNPJ AS CPF
		,M.MASCARA_CPF AS MASCARA_CPF
		,C.DT_NASCIMENTO AS DATA_DE_NASCIMENTO
		,C.DS_GENERO AS GENERO
		,C.DS_BAIRRO_RES AS BAIRRO
		,C.DS_CIDADE_RES AS CIDADE
		,C.DS_UF_RES AS UF
		,V.ID_COMPRA AS PEDIDO
		,V.ID_PRODUTO AS SKU
		,CP.MATERIAL_CODIGO AS SKU_SEM_DISTINCAO_DE_TAMANHO
		,CP.MATERIAL_PAI_DESCRICAO AS DESCRICAO_PRODUTO
		,CP.DEPARTAMENTO AS DEPARTAMENTO
		,CP.MATERIAL_SEGMENTO AS SEGMENTO
		,CP.[MATERIAL_SUBSEGMENTO] AS SUBSEGMENTO
		,CP.[MATERIAL_GRUPO] AS GRUPO
		,CP.[MATERIAL_SUBGRUPO] AS SUBGRUPO
		,CP.[MATERIAL_MARCA] AS MARCA
		,CP.[MATERIAL_TAMANHO] AS TAMANHO
		,CAST(V.DATA_COMPRA AS date) AS DATA_COMPRA
		,V.QUANTIDADE_PRODUTO AS QUANTIDADE_POR_ITENS
		,V.TOTAL_VALOR_LIQUIDO AS TOTAL
		,V.QUANTIDADE_TOTAL_PRODUTO AS QUANTIDADE_TOTAL_CUPOM
		,V.METODO_PAGAMENTO AS METODO_DE_PAGAMENTO INTO #AMOSTRA
	FROM CRM_DATALAKE.CRM.TRANSACIONAL_VENDA AS V
	LEFT JOIN CRM_DATALAKE.CRM.CLIENTES AS C
		ON V.CPF_CNPJ = C.NU_CPF 
	LEFT JOIN CRM_DATALAKE.CRM.CATALOGO_PRODUTOS AS CP
		ON V.ID_PRODUTO = CP.MATERIAL_CODIGO
	LEFT JOIN #MASCARA AS M
		ON V.CPF_CNPJ = M.CPF
	WHERE CAST(V.DATA_COMPRA AS date) BETWEEN '2021-01-01' AND '2022-02-28'
		AND ID_LOJA = '1119'
		AND OPERACAO_PRODUTO LIKE '%COMPRA%'
		--AND MASCARA_CPF IS NULL

SELECT LEFT(DATA_COMPRA,7), SUM(CAST(TOTAL AS float))
FROM(
SELECT DISTINCT DATA_COMPRA, PEDIDO, TOTAL
	FROM #AMOSTRA) AS T
	GROUP BY LEFT(DATA_COMPRA,7)
	ORDER BY 1