
--------------------------- NUMEROS PARA O COMPARATIVO DIARIO COM OS DADOS DE RECEITA INFLUENCIADA ---------------------------
IF OBJECT_ID('tempDB..#COMPARATIVO_DIA', 'U') IS NOT NULL DROP TABLE #COMPARATIVO_DIA

SELECT DISTINCT
		CAST(DATA_COMPRA AS date) AS DATA_COMPRA
		,ID_LOJA
		,ID_COMPRA
		,CASE WHEN CPF_CNPJ IS NOT NULL THEN 1 ELSE 0 END AS COMPRAS_INDENTIFICADAS
		,TOTAL_VALOR_LIQUIDO INTO #COMPARATIVO_DIA
	FROM CRM_DATALAKE.CRM.TRANSACIONAL_VENDA
	WHERE OPERACAO_PRODUTO LIKE '%COMPRA%' 
		AND ID_LOJA IS NOT NULL
		AND CAST(DATA_COMPRA AS DATE) >= '2021-03-01'

SELECT
		ID_LOJA
		,DATA_COMPRA
		,COMPRAS_INDENTIFICADAS
		,COUNT(DISTINCT ID_COMPRA) AS QTD_CUPONS
		,SUM(CAST(TOTAL_VALOR_LIQUIDO AS numeric(10,2))) AS TOTAL_VALOR_LIQUIDO
	FROM #COMPARATIVO_DIA
	GROUP BY 
		ID_LOJA
		,DATA_COMPRA
		,COMPRAS_INDENTIFICADAS
	ORDER BY 5 DESC






