-----------------------  DADOS DAS CAMPANHAS  -----------------------------------
SELECT 
		C.ID_CAMPANHA
		,A.DATA_ENVIO
		,C.NOME_CAMPANHA
		,C.DESCRICAO_CAMPANHA
		,A.TIPO_COMUNICACAO
		,C.SOFTWARE
		,C.QTD_ENVIADA
		,C.QTD_ENTREGAS
		,C.QTD_DESCADASTROS
		,COUNT(DISTINCT CONCAT(A.CPF, A.EMAIL, A.TELEFONE)) AS QTD_ABERTOS
	FROM CRM_DATALAKE.CRM.CAMPANHAS_STZ AS C 
	LEFT JOIN CRM_DATALAKE.CRM.ABERTOS_STZ AS A
		ON C.ID_CAMPANHA = A.ID_CAMPANHA
	WHERE ((DATA_ENVIO >= '2021-03-01' AND DATA_CAMPANHA <= GETDATE()) OR DATA_CAMPANHA IS NULL)
	GROUP BY
		C.ID_CAMPANHA
		,A.DATA_ENVIO
		,C.NOME_CAMPANHA
		,C.DESCRICAO_CAMPANHA
		,C.SOFTWARE
		,C.QTD_ENVIADA
		,C.QTD_ENTREGAS
		,C.QTD_DESCADASTROS
		,A.TIPO_COMUNICACAO