IF OBJECT_ID('tempDB..#VENDAS','U') IS NOT NULL	DROP TABLE #VENDAS
IF OBJECT_ID('tempDB..#ABERTOS','U') IS NOT NULL DROP TABLE #ABERTOS
IF OBJECT_ID('tempDB..#ABERTOS_AUX','U') IS NOT NULL DROP TABLE #ABERTOS_AUX
IF OBJECT_ID('tempDB..#RESULTADOS','U') IS NOT NULL	DROP TABLE #RESULTADOS
IF OBJECT_ID('tempDB..#AMOSTRA','U') IS NOT NULL	DROP TABLE #AMOSTRA
IF OBJECT_ID('tempDB..#CLIENTE_AUX','U') IS NOT NULL	DROP TABLE #CLIENTE_AUX
IF OBJECT_ID('tempDB..#SALESFORCE_AUX','U') IS NOT NULL	DROP TABLE #SALESFORCE_AUX

SELECT DISTINCT
		ID_COMPRA
		,CPF_CNPJ
		,DATA_COMPRA INTO #VENDAS
	FROM CRM_DATALAKE.CRM.TRANSACIONAL_VENDA (NOLOCK)
	WHERE CPF_CNPJ IS NOT NULL
		AND NOME_LOJA IN ('SITE','STUDIO Z')
		AND OPERACAO_PRODUTO LIKE '%COMPRA%'

SELECT
		A.ID_CAMPANHA
		,C.NOME_CAMPANHA
		,A.CPF
		,A.EMAIL
		,A.TELEFONE
		,A.CONTACT_KEY 
		,A.TIPO_COMUNICACAO
		,A.LOJA_PREFERENCIA
		,A.DATA_ENVIO
		,A.DATA_ABERTURA INTO #ABERTOS_AUX
	FROM CRM_DATALAKE.CRM.ABERTOS_STZ (NOLOCK) AS A
	LEFT JOIN CRM_DATALAKE.CRM.CAMPANHAS_STZ AS C
		ON A.ID_CAMPANHA = C.ID_CAMPANHA
	WHERE ISNULL(A.EMAIL,'') != 'migracao@calcard.com.br'
		--AND TIPO_COMUNICACAO = 'WHATSAPP'
		--AND CAST(A.DATA_ENVIO AS date) BETWEEN '2022-02-25' AND '2022-03-23'

SELECT NU_CPF, DS_EMAIL INTO #CLIENTE_AUX
	FROM CRM_DATALAKE.CRM.CLIENTES
	WHERE (NU_CPF IS NOT NULL AND DS_EMAIL IS NOT NULL)

SELECT * INTO #SALESFORCE_AUX
	FROM CRM_DATALAKE.CRM.CADASTRO_SALESFORCE
	WHERE (CPF IS NOT NULL AND CONTACT_KEY IS NOT NULL)

SELECT
		A.ID_CAMPANHA
		,A.NOME_CAMPANHA
		,COALESCE(A.CPF,C1.NU_CPF, CS.CPF) AS CPF
		,A.EMAIL
		,A.TELEFONE
		,A.CONTACT_KEY 
		,A.LOJA_PREFERENCIA
		,A.TIPO_COMUNICACAO
		,A.DATA_ENVIO
		,A.DATA_ABERTURA INTO #ABERTOS
	FROM #ABERTOS_AUX AS A
	LEFT JOIN #CLIENTE_AUX (NOLOCK) AS C1
		ON A.EMAIL = C1.DS_EMAIL
	LEFT JOIN #SALESFORCE_AUX (NOLOCK) AS CS
		ON A.CONTACT_KEY = CS.CONTACT_KEY
	WHERE DATEDIFF(DAY, A.DATA_ENVIO, A.DATA_ABERTURA) IN (0,1,2)

SELECT * INTO #RESULTADOS
FROM (
	SELECT *
	, PRIORIDADE = ROW_NUMBER() OVER (
				  PARTITION BY CPF, EMAIL, ID_COMPRA
				  ORDER BY DATA_COMPRA DESC,DIFERENCAS_DIAS ASC, DATA_ABERTURA DESC, TIPO_CAMPANHA ASC, ID_CAMPANHA ASC)
		FROM (SELECT DISTINCT
				A.CPF
				,A.EMAIL
				,A.TELEFONE
				,A.CONTACT_KEY
				,A.LOJA_PREFERENCIA
				,A.ID_CAMPANHA
				,A.NOME_CAMPANHA
				,CASE 
					WHEN A.TIPO_COMUNICACAO = 'Whatsapp' THEN '1-Whatsapp'
					WHEN A.TIPO_COMUNICACAO = 'BTG' THEN '2-BTG'
					WHEN A.TIPO_COMUNICACAO = 'Segmentado' THEN '3-Segmentado'
					WHEN A.TIPO_COMUNICACAO = 'Relação' THEN '4-Relacionamento'
					WHEN A.TIPO_COMUNICACAO = 'BLAST' THEN '5-BLAST'
					WHEN A.TIPO_COMUNICACAO = 'SMS' THEN '6-SMS'
					WHEN A.TIPO_COMUNICACAO = 'PUSH' THEN '7-PUSH'
					ELSE '8-Conferir'
				END AS TIPO_CAMPANHA
				,A.DATA_ENVIO
				,A.DATA_ABERTURA
				,V.DATA_COMPRA
				,DATEDIFF(DAY,DATA_ABERTURA, DATA_COMPRA) AS DIFERENCAS_DIAS
				,V.ID_COMPRA		
			FROM #ABERTOS AS A
			JOIN #VENDAS AS V
				ON V.CPF_CNPJ = A.CPF
				AND A.DATA_ABERTURA <= V.DATA_COMPRA
			WHERE DATEDIFF(DAY, DATA_ENVIO, DATA_COMPRA) <=6
	) AS T ) AS RANKEADO
	WHERE PRIORIDADE = 1


SELECT DISTINCT
		PRIORIDADE
		,DIFERENCAS_DIAS
		,R.CPF
		,R.EMAIL
		,R.ID_CAMPANHA
		,R.NOME_CAMPANHA
		,R.TIPO_CAMPANHA
		,CAST(R.DATA_ENVIO AS date) AS DATA_ENVIO
		,CAST(R.DATA_ABERTURA AS date) AS DATA_ABERTURA
		,CAST(R.DATA_COMPRA AS date) AS DATA_COMPRA
		,T.ID_LOJA
		,R.LOJA_PREFERENCIA
		,R.ID_COMPRA
		,T.ID_PRODUTO
		,CP.[ORGANIZACAO_NO]
		,CP.[DEPARTAMENTO]
		,CP.[MATERIAL_SEGMENTO]
		,CP.[MATERIAL_SUBSEGMENTO]
		,CP.[MATERIAL_GRUPO]
		,CP.[MATERIAL_SUBGRUPO]
		,CP.[MATERIAL_PAI_DESCRICAO]
		,CP.[MATERIAL_CODIGO]
		,CP.[MATERIAL_MARCA]
		,CP.[MATERIAL_TAMANHO]
		,CP.[MATERIAL_PAI_CODIGO]
		,T.QUANTIDADE_PRODUTO
		,CAST(T.TOTAL_VALOR_LIQUIDO AS float) AS TOTAL_VALOR_LIQUIDO
		,CAST(T.TOTAL_PRECO_PRODUTO_RATEADO AS float) AS TOTAL_PRECO_PRODUTO_RATEADO
		,CAST(T.TOTAL_PRECO_PRODUTO_BRUTO  AS float)  AS TOTAL_PRECO_PRODUTO_BRUTO 
		INTO #AMOSTRA
	FROM #RESULTADOS AS R
	JOIN CRM_DATALAKE.CRM.TRANSACIONAL_VENDA (NOLOCK) AS T
		ON R.ID_COMPRA = T.ID_COMPRA
	LEFT JOIN CRM_DATALAKE.CRM.CATALOGO_PRODUTOS (NOLOCK) AS CP
		ON T.ID_PRODUTO = CP.MATERIAL_CODIGO

SELECT *
	FROM #AMOSTRA