
--------------------------- NUMEROS PARA O COMPARATIVO DIARIO COM OS DADOS DE RECEITA INFLUENCIADA ---------------------------
IF OBJECT_ID('tempDB..#COMPARATIVO_DIA', 'U') IS NOT NULL DROP TABLE #COMPARATIVO_DIA

SELECT DISTINCT
		CAST(DATA_COMPRA AS date) AS DATA_COMPRA
		,ID_LOJA
		,ID_COMPRA
		,CASE WHEN CPF_CNPJ IS NOT NULL THEN 1 ELSE 0 END AS COMPRAS_INDENTIFICADAS
		,TOTAL_VALOR_LIQUIDO INTO #COMPARATIVO_DIA
	FROM CRM_DATALAKE.CRM.TRANSACIONAL_VENDA
	WHERE OPERACAO_PRODUTO LIKE '%COMPRA%' 
		AND ID_LOJA IS NOT NULL
		AND CAST(DATA_COMPRA AS DATE) >= '2021-01-01'

SELECT
		ID_LOJA
		,DATA_COMPRA
		,COMPRAS_INDENTIFICADAS
		,COUNT(DISTINCT ID_COMPRA) AS QTD_CUPONS
		,SUM(CAST(TOTAL_VALOR_LIQUIDO AS numeric(10,2))) AS TOTAL_VALOR_LIQUIDO
	FROM #COMPARATIVO_DIA
	GROUP BY 
		ID_LOJA
		,DATA_COMPRA
		,COMPRAS_INDENTIFICADAS
	ORDER BY 5 DESC


--------------------------- QUANTIDADE DE ABERTOS ---------------------------
SELECT DISTINCT TOP 10
		LEFT(CAST(DATA_ENVIO AS DATE),7)+'-01' as DATA_ENVIO
		,ID_CAMPANHA
		,CONCAT(CPF, EMAIL,TELEFONE) AS CLIENTE_QUE_ABRIU
	FROM CRM_DATALAKE.CRM.ABERTOS_STZ
	WHERE CAST(DATA_ENVIO AS date)>='2021-01-01'

-----------------------  DADOS DAS CAMPANHAS  -----------------------------------
SELECT 
		C.ID_CAMPANHA
		,A.DATA_ENVIO
		,C.NOME_CAMPANHA
		,C.DESCRICAO_CAMPANHA
		,A.TIPO_COMUNICACAO
		,C.SOFTWARE
		,C.QTD_ENVIADA
		,C.QTD_ENTREGAS
		,C.QTD_DESCADASTROS
		,COUNT(DISTINCT CONCAT(A.CPF, A.EMAIL, A.TELEFONE)) AS QTD_ABERTOS
	FROM CRM_DATALAKE.CRM.CAMPANHAS_STZ AS C 
	LEFT JOIN CRM_DATALAKE.CRM.ABERTOS_STZ AS A
		ON C.ID_CAMPANHA = A.ID_CAMPANHA
	WHERE ((DATA_ENVIO >= '2021-03-01' AND DATA_CAMPANHA <= GETDATE()) OR DATA_CAMPANHA IS NULL)
	GROUP BY
		C.ID_CAMPANHA
		,A.DATA_ENVIO
		,C.NOME_CAMPANHA
		,C.DESCRICAO_CAMPANHA
		,C.SOFTWARE
		,C.QTD_ENVIADA
		,C.QTD_ENTREGAS
		,C.QTD_DESCADASTROS
		,A.TIPO_COMUNICACAO

